/**
 * Realistic networking appliance data with specs, features, and pricing
 */

import type { ComparisonDevice, DecisionNode } from './appliances-types';

export const networkDevices: ComparisonDevice[] = [
  {
    id: 'cisco-isr-4331',
    name: 'Cisco ISR 4331',
    type: 'router',
    category: 'physical',
    manufacturer: 'Cisco',
    model: 'ISR 4331',
    specs: {
      throughput: '100-300 Mbps',
      maxConnections: 5000,
      portCount: 3,
      rackUnits: 1,
      powerConsumption: '50-75W',
      memoryGB: 4,
      storageGB: 8,
      redundancy: true,
      hotSwappable: false,
    },
    features: {
      layer3Routing: true,
      vlanSupport: true,
      qosCapabilities: true,
      vpnSupport: true,
      loadBalancing: false,
      highAvailability: true,
      deepPacketInspection: false,
      threatPrevention: false,
      webFiltering: false,
      applicationControl: false,
    },
    pricing: {
      initialCost: 3500,
      annualMaintenanceCost: 500,
      powerCostPerYear: 65,
      totalCostYear1: 4065,
      totalCost3Years: 5565,
      totalCost5Years: 6565,
    },
    useCase: ['Branch office connectivity', 'WAN aggregation', 'VPN termination'],
    pros: [
      'Proven reliability',
      'Extensive protocol support',
      'Strong security features',
      'Good performance for branch offices',
    ],
    cons: [
      'Higher upfront cost',
      'Complex configuration',
      'Requires specialized knowledge',
      'Limited scalability without upgrades',
    ],
  },
  {
    id: 'pfsense-virtual',
    name: 'pfSense Virtual Firewall',
    type: 'firewall-stateful',
    category: 'virtual',
    manufacturer: 'Netgate',
    model: 'pfSense CE',
    specs: {
      throughput: '1-10 Gbps',
      maxConnections: 50000,
      portCount: 0,
      rackUnits: 0,
      powerConsumption: '0W (VM)',
      memoryGB: 8,
      storageGB: 20,
      redundancy: true,
      hotSwappable: true,
    },
    features: {
      layer3Routing: true,
      vlanSupport: true,
      qosCapabilities: true,
      vpnSupport: true,
      loadBalancing: true,
      highAvailability: true,
      deepPacketInspection: true,
      threatPrevention: true,
      webFiltering: true,
      applicationControl: true,
    },
    pricing: {
      initialCost: 0,
      annualMaintenanceCost: 399,
      powerCostPerYear: 0,
      totalCostYear1: 399,
      totalCost3Years: 1197,
      totalCost5Years: 1995,
    },
    useCase: ['Small to medium business firewall', 'VPN gateway', 'Traffic shaping'],
    pros: [
      'Zero hardware cost',
      'Rapid deployment',
      'Easy scaling',
      'Active community support',
      'Flexible configuration',
    ],
    cons: [
      'Requires hypervisor infrastructure',
      'Performance depends on host',
      'Less vendor support than commercial options',
    ],
  },
  {
    id: 'fortinet-fg-100f',
    name: 'FortiGate 100F',
    type: 'firewall-stateful',
    category: 'physical',
    manufacturer: 'Fortinet',
    model: 'FG-100F',
    specs: {
      throughput: '10 Gbps',
      maxConnections: 500000,
      portCount: 18,
      rackUnits: 1,
      powerConsumption: '35W',
      memoryGB: 4,
      storageGB: 240,
      redundancy: true,
      hotSwappable: true,
    },
    features: {
      layer3Routing: true,
      vlanSupport: true,
      qosCapabilities: true,
      vpnSupport: true,
      loadBalancing: true,
      highAvailability: true,
      deepPacketInspection: true,
      threatPrevention: true,
      webFiltering: true,
      applicationControl: true,
    },
    pricing: {
      initialCost: 1800,
      annualMaintenanceCost: 650,
      powerCostPerYear: 38,
      totalCostYear1: 2488,
      totalCost3Years: 3788,
      totalCost5Years: 5088,
    },
    useCase: ['SMB perimeter security', 'SD-WAN', 'Secure remote access'],
    pros: [
      'High performance',
      'Comprehensive security features',
      'Integrated threat intelligence',
      'Good price-to-performance ratio',
    ],
    cons: [
      'Annual subscription required',
      'Complex initial setup',
      'Interface can be overwhelming',
    ],
  },
  {
    id: 'cisco-catalyst-9300',
    name: 'Cisco Catalyst 9300',
    type: 'switch',
    category: 'physical',
    manufacturer: 'Cisco',
    model: 'C9300-48P',
    specs: {
      throughput: '176 Gbps',
      maxConnections: 32000,
      portCount: 48,
      rackUnits: 1,
      powerConsumption: '740W (PoE)',
      memoryGB: 8,
      storageGB: 32,
      redundancy: true,
      hotSwappable: true,
    },
    features: {
      layer3Routing: true,
      vlanSupport: true,
      qosCapabilities: true,
      vpnSupport: false,
      loadBalancing: false,
      highAvailability: true,
      deepPacketInspection: false,
      threatPrevention: false,
      webFiltering: false,
      applicationControl: false,
    },
    pricing: {
      initialCost: 12000,
      annualMaintenanceCost: 1200,
      powerCostPerYear: 810,
      totalCostYear1: 14010,
      totalCost3Years: 16410,
      totalCost5Years: 18810,
    },
    useCase: ['Campus access layer', 'PoE for IP phones/cameras', 'IoT connectivity'],
    pros: [
      'High port density',
      'PoE+ support',
      'Stackable design',
      'Advanced security features',
      'SD-Access ready',
    ],
    cons: [
      'Expensive upfront cost',
      'Requires DNA licensing for full features',
      'Overkill for small deployments',
    ],
  },
  {
    id: 'f5-big-ip-virtual',
    name: 'F5 BIG-IP Virtual Edition',
    type: 'load-balancer',
    category: 'virtual',
    manufacturer: 'F5',
    model: 'BIG-IP VE',
    specs: {
      throughput: '200 Mbps - 10 Gbps',
      maxConnections: 10000000,
      portCount: 0,
      rackUnits: 0,
      powerConsumption: '0W (VM)',
      memoryGB: 16,
      storageGB: 160,
      redundancy: true,
      hotSwappable: true,
    },
    features: {
      layer3Routing: true,
      vlanSupport: true,
      qosCapabilities: true,
      vpnSupport: true,
      loadBalancing: true,
      highAvailability: true,
      deepPacketInspection: true,
      threatPrevention: true,
      webFiltering: false,
      applicationControl: true,
    },
    pricing: {
      initialCost: 5000,
      annualMaintenanceCost: 2000,
      powerCostPerYear: 0,
      totalCostYear1: 7000,
      totalCost3Years: 11000,
      totalCost5Years: 15000,
    },
    useCase: ['Application delivery controller', 'SSL offloading', 'Web application firewall'],
    pros: [
      'Industry-leading ADC',
      'Flexible licensing',
      'Cloud-native deployment',
      'Extensive protocol support',
    ],
    cons: ['Expensive licensing', 'Steep learning curve', 'Can be resource-intensive'],
  },
  {
    id: 'palo-alto-vm-series',
    name: 'Palo Alto VM-Series',
    type: 'firewall-ngfw',
    category: 'virtual',
    manufacturer: 'Palo Alto',
    model: 'VM-50',
    specs: {
      throughput: '500 Mbps',
      maxConnections: 64000,
      portCount: 0,
      rackUnits: 0,
      powerConsumption: '0W (VM)',
      memoryGB: 6.5,
      storageGB: 60,
      redundancy: true,
      hotSwappable: true,
    },
    features: {
      layer3Routing: true,
      vlanSupport: true,
      qosCapabilities: true,
      vpnSupport: true,
      loadBalancing: false,
      highAvailability: true,
      deepPacketInspection: true,
      threatPrevention: true,
      webFiltering: true,
      applicationControl: true,
    },
    pricing: {
      initialCost: 3500,
      annualMaintenanceCost: 1200,
      powerCostPerYear: 0,
      totalCostYear1: 4700,
      totalCost3Years: 7100,
      totalCost5Years: 9500,
    },
    useCase: ['Cloud security', 'Multi-cloud connectivity', 'Microsegmentation'],
    pros: [
      'Best-in-class threat prevention',
      'Cloud-native design',
      'Consistent policy across environments',
      'Easy scaling',
    ],
    cons: [
      'Expensive subscriptions',
      'Performance depends on VM resources',
      'Complex pricing model',
    ],
  },
  {
    id: 'ubiquiti-dream-machine-pro',
    name: 'UniFi Dream Machine Pro',
    type: 'router',
    category: 'physical',
    manufacturer: 'Ubiquiti',
    model: 'UDM-Pro',
    specs: {
      throughput: '3.5 Gbps',
      maxConnections: 10000,
      portCount: 8,
      rackUnits: 1,
      powerConsumption: '26W',
      memoryGB: 4,
      storageGB: 128,
      redundancy: true,
      hotSwappable: false,
    },
    features: {
      layer3Routing: true,
      vlanSupport: true,
      qosCapabilities: true,
      vpnSupport: true,
      loadBalancing: false,
      highAvailability: false,
      deepPacketInspection: true,
      threatPrevention: true,
      webFiltering: false,
      applicationControl: false,
    },
    pricing: {
      initialCost: 379,
      annualMaintenanceCost: 0,
      powerCostPerYear: 28,
      totalCostYear1: 407,
      totalCost3Years: 463,
      totalCost5Years: 519,
    },
    useCase: ['Small business all-in-one', 'Home office', 'Remote site'],
    pros: [
      'All-in-one solution',
      'No licensing fees',
      'User-friendly interface',
      'Good performance for price',
      'Built-in NVR',
    ],
    cons: [
      'Limited enterprise features',
      'No phone support',
      'Single point of failure',
      'Limited redundancy options',
    ],
  },
  {
    id: 'aws-transit-gateway',
    name: 'AWS Transit Gateway',
    type: 'router',
    category: 'cloud',
    manufacturer: 'Amazon',
    model: 'Transit Gateway',
    specs: {
      throughput: 'Up to 50 Gbps per VPC',
      maxConnections: 5000,
      portCount: 0,
      rackUnits: 0,
      powerConsumption: '0W (Cloud)',
      memoryGB: 0,
      storageGB: 0,
      redundancy: true,
      hotSwappable: true,
    },
    features: {
      layer3Routing: true,
      vlanSupport: false,
      qosCapabilities: false,
      vpnSupport: true,
      loadBalancing: true,
      highAvailability: true,
      deepPacketInspection: false,
      threatPrevention: false,
      webFiltering: false,
      applicationControl: false,
    },
    pricing: {
      initialCost: 0,
      annualMaintenanceCost: 4380, // $0.05/hour + data transfer
      powerCostPerYear: 0,
      totalCostYear1: 4380,
      totalCost3Years: 13140,
      totalCost5Years: 21900,
    },
    useCase: ['Multi-VPC connectivity', 'Hybrid cloud', 'Cloud WAN'],
    pros: [
      'No hardware to manage',
      'Automatic scaling',
      'Native AWS integration',
      'High availability built-in',
    ],
    cons: [
      'Ongoing operational costs',
      'AWS vendor lock-in',
      'Data transfer costs add up',
      'Limited protocol support',
    ],
  },
];

export const decisionTreeData: Map<string, DecisionNode> = new Map([
  [
    'start',
    {
      id: 'start',
      type: 'question',
      text: 'Do you already have virtualization infrastructure (VMware, Hyper-V, KVM)?',
      yesPath: 'budget-check',
      noPath: 'new-infra',
    },
  ],
  [
    'budget-check',
    {
      id: 'budget-check',
      type: 'question',
      text: 'Is your budget for networking equipment less than $10,000?',
      yesPath: 'virtual-recommend',
      noPath: 'performance-critical',
    },
  ],
  [
    'new-infra',
    {
      id: 'new-infra',
      type: 'question',
      text: 'Are you planning to deploy cloud infrastructure (AWS, Azure, GCP)?',
      yesPath: 'cloud-native',
      noPath: 'physical-required',
    },
  ],
  [
    'virtual-recommend',
    {
      id: 'virtual-recommend',
      type: 'question',
      text: 'Do you need more than 5 Gbps of throughput for a single device?',
      yesPath: 'hybrid-approach',
      noPath: 'virtual-best',
    },
  ],
  [
    'performance-critical',
    {
      id: 'performance-critical',
      type: 'question',
      text: 'Is network performance critical with sub-millisecond latency requirements?',
      yesPath: 'physical-best',
      noPath: 'hybrid-approach',
    },
  ],
  [
    'cloud-native',
    {
      id: 'cloud-native',
      type: 'recommendation',
      text: 'Cloud-Native Virtual Appliances',
      devices: ['aws-transit-gateway', 'palo-alto-vm-series', 'f5-big-ip-virtual'],
      rationale:
        'Cloud-native virtual appliances offer seamless integration with cloud providers, automatic scaling, and pay-as-you-go pricing. Deploy VM-Series firewalls in AWS/Azure or use native services like AWS Transit Gateway for optimal cloud performance.',
    },
  ],
  [
    'physical-required',
    {
      id: 'physical-required',
      type: 'question',
      text: 'Do you need PoE (Power over Ethernet) for phones, cameras, or access points?',
      yesPath: 'physical-with-poe',
      noPath: 'small-physical',
    },
  ],
  [
    'virtual-best',
    {
      id: 'virtual-best',
      type: 'recommendation',
      text: 'Virtual Appliances (Cost-Effective)',
      devices: ['pfsense-virtual', 'palo-alto-vm-series', 'f5-big-ip-virtual'],
      rationale:
        'Virtual appliances provide excellent value for most use cases. Deploy pfSense for firewall/routing, Palo Alto VM-Series for advanced security, or F5 BIG-IP VE for load balancing. Total cost of ownership is significantly lower than physical appliances.',
    },
  ],
  [
    'hybrid-approach',
    {
      id: 'hybrid-approach',
      type: 'recommendation',
      text: 'Hybrid Approach (Best of Both Worlds)',
      devices: ['cisco-isr-4331', 'pfsense-virtual', 'fortinet-fg-100f', 'palo-alto-vm-series'],
      rationale:
        'Combine physical and virtual appliances for optimal flexibility. Use physical devices for core routing and high-throughput workloads, while deploying virtual appliances for security functions, testing, and rapid scaling. This approach balances performance with cost-effectiveness.',
    },
  ],
  [
    'physical-best',
    {
      id: 'physical-best',
      type: 'recommendation',
      text: 'Physical Appliances (Maximum Performance)',
      devices: ['cisco-catalyst-9300', 'fortinet-fg-100f', 'cisco-isr-4331'],
      rationale:
        'Physical appliances deliver predictable, maximum performance for mission-critical applications. Cisco Catalyst switches provide line-rate switching with PoE, while FortiGate firewalls offer dedicated ASICs for deep packet inspection at multi-gigabit speeds.',
    },
  ],
  [
    'physical-with-poe',
    {
      id: 'physical-with-poe',
      type: 'recommendation',
      text: 'Physical Switches with PoE',
      devices: ['cisco-catalyst-9300', 'ubiquiti-dream-machine-pro'],
      rationale:
        'PoE requirements necessitate physical switches. Cisco Catalyst 9300 provides enterprise-grade performance with 48 PoE+ ports, while UniFi Dream Machine Pro offers an affordable all-in-one solution for smaller deployments with 8 PoE ports.',
    },
  ],
  [
    'small-physical',
    {
      id: 'small-physical',
      type: 'recommendation',
      text: 'Compact Physical Appliances',
      devices: ['ubiquiti-dream-machine-pro', 'fortinet-fg-100f'],
      rationale:
        'For small to medium deployments without virtualization infrastructure, compact physical appliances offer the best value. UniFi Dream Machine Pro provides all-in-one routing, switching, and security for under $400, while FortiGate 100F delivers enterprise features at an accessible price point.',
    },
  ],
]);

export const deviceTemplates = {
  router: {
    icon: '🔀',
    defaultSpecs: {
      throughput: '1 Gbps',
      maxConnections: 1000,
      powerConsumption: '50W',
      redundancy: false,
      hotSwappable: false,
    },
  },
  switch: {
    icon: '🔌',
    defaultSpecs: {
      throughput: '10 Gbps',
      maxConnections: 8000,
      portCount: 24,
      powerConsumption: '100W',
      redundancy: false,
      hotSwappable: false,
    },
  },
  firewall: {
    icon: '🛡️',
    defaultSpecs: {
      throughput: '2 Gbps',
      maxConnections: 50000,
      powerConsumption: '75W',
      redundancy: true,
      hotSwappable: false,
    },
  },
  'load-balancer': {
    icon: '⚖️',
    defaultSpecs: {
      throughput: '5 Gbps',
      maxConnections: 100000,
      powerConsumption: '60W',
      redundancy: true,
      hotSwappable: false,
    },
  },
  'wireless-controller': {
    icon: '📡',
    defaultSpecs: {
      throughput: '1 Gbps',
      maxConnections: 500,
      powerConsumption: '40W',
      redundancy: false,
      hotSwappable: false,
    },
  },
};
